### ISSUE TITLE
cURL call failed

### ISSUE THREAD

**Issue by jamalnasir** [2Checkout/2checkout-php#15]

**Comment by floreadm** [comment]
can we open this?
i have this error with sandbox.

Unknown SSL protocol error in connection to sandbox.2checkout.com:443
Warning: curl_error(): 290 is not a valid cURL handle resource in /var/www/vhosts/escapebooker.com/httpdocs/app/webroot/ts/lib/Twocheckout/Api/TwocheckoutApi.php on line 56

**Comment by craigchristenson** [comment]
The 2Checkout sandbox only supports TLS 1.1 and 1.2 protocols. This library should have no issues supporting those protocols. Can you check what version of PHP and OpenSSL you are running?
`php -v`
`openssl version`

**Comment by floreadm** [comment]
Hi.

We are running PHP 5.3.3

and OpenSSL 0.9.8e-fips-rhel5

are those ok?

On Thu, Jan 14, 2016 at 6:37 AM, Craig Christenson <notifications@github.com
> wrote:

> The 2Checkout sandbox only supports TLS 1.1 and 1.2 protocols. This
> library should have no issues supporting those protocols. Can you check
> what version of PHP and OpenSSL you are running?
> php -v
> openssl version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2Checkout/2checkout-php/issues/15#issuecomment-171527904>
> .
>



-- 

[image: Happy Digital] <http://behappydigital.com>

Daniel Florea / Senior Web Developer
dani@behappydigital.com

Happy Digital
Tel: +40746049008
str. Gheorghe Titeica, nr. 8
Bucuresti, Romania
http://behappydigital.com

[image: Facebook] <https://www.facebook.com/behappydigital> [image: Twitter]
<https://twitter.com/behappydigital> [image: Google Plus]
<https://plus.google.com/+HappyDigitalBucuresti> [image: Linkedin]
<https://www.linkedin.com/company/happy-digital> [image: Skype]
<http://behappydigital.com/skype/>

**Comment by craigchristenson** [comment]
Your PHP version is fine but it looks like OpenSSL added support for TLS v1.1 & TLS v1.2 in v1.0.1.
[Major changes between OpenSSL 1.0.0h and OpenSSL 1.0.1]
(https://www.openssl.org/news/openssl-1.0.1-notes.html)
